// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RegressionLab.Data;

#nullable disable

namespace RegressionLab.Data.Migrations
{
    [DbContext(typeof(LabDbContext))]
    partial class LabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RegressionLab.Domain.RuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, string>>("ArraySortKeys")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("DynamicPatterns")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("IgnoreHeaders")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("IgnorePaths")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("NumericAbsTolerance")
                        .HasColumnType("double precision");

                    b.Property<double>("NumericRelTolerance")
                        .HasColumnType("double precision");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("RuleSets");
                });

            modelBuilder.Entity("RegressionLab.Domain.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaselineBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CandidateBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompletedScenarios")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiffCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NetworkFailureCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RuleSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("RuleSetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RuleSetVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RuleSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScenarios")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("RegressionLab.Domain.RunResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Baseline")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Candidate")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diffs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScenarioName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunResults");
                });

            modelBuilder.Entity("RegressionLab.Domain.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Dictionary<string, string>>("Headers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("JsonBody")
                        .HasColumnType("text");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Dictionary<string, string>>("PathParameters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PathTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Dictionary<string, string>>("QueryParameters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RuleSetId")
                        .HasColumnType("uuid");

                    b.Property<List<string>>("SecretRefs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("RuleSetId");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("RegressionLab.Domain.Run", b =>
                {
                    b.OwnsOne("RegressionLab.Domain.RunOptions", "Options", b1 =>
                        {
                            b1.Property<Guid>("RunId")
                                .HasColumnType("uuid");

                            b1.Property<double>("BaselineRateLimit")
                                .HasColumnType("double precision");

                            b1.Property<double>("CandidateRateLimit")
                                .HasColumnType("double precision");

                            b1.Property<int>("Concurrency")
                                .HasColumnType("integer");

                            b1.Property<int>("TimeoutMs")
                                .HasColumnType("integer");

                            b1.HasKey("RunId");

                            b1.ToTable("Runs");

                            b1.ToJson("options");

                            b1.WithOwner()
                                .HasForeignKey("RunId");
                        });

                    b.Navigation("Options")
                        .IsRequired();
                });

            modelBuilder.Entity("RegressionLab.Domain.RunResult", b =>
                {
                    b.HasOne("RegressionLab.Domain.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegressionLab.Domain.Scenario", b =>
                {
                    b.HasOne("RegressionLab.Domain.RuleSet", "RuleSet")
                        .WithMany("Scenarios")
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RuleSet");
                });

            modelBuilder.Entity("RegressionLab.Domain.RuleSet", b =>
                {
                    b.Navigation("Scenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
